server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver




    url: jdbc:oracle:thin:@localhost:1521:Anhphuc9969
    username: DEMOITSOL
    password: 123456


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: cutetiger98.java@gmail.com
    password: vkqingjddopedqbw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: info
  file:
    name: ./log.txt
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'

application:
  active-account:
    active-url: "http://localhost:8080/active/"
